# version: "3"
# services:
#   back:
#     build:
#       context: .
#       target: runner
#     volumes:
#       - ./:/app
#     ports:
#       - "80:3630"
#     environment:
#       - PORT=3630
#       - BDD_URL=mariadb://gautier:123456@database/ask_db
#       - NODE_ENV=production
#     command: ["npm", "run", "dev"]
#   database:
#     image: mariadb
#     restart: always
#     environment:
#       MARIADB_ROOT_PASSWORD: password
#       MARIADB_DATABASE: ask_db
#       MARIADB_USERNAME: gautier
#       MARIADB_PASSWORD: 123456

version: "3"

services:
  web:
    build:
      context: .
      target: runner
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=production
      - BDD_URL=mariadb://ask:ask@database/database
      - PORT=3630
    command: ["npm", "run", "dev"]
    ports:
      - 3630:3630

  database:
    image: mariadb:10.6
    ports:
      - 3631:3306
    environment:
      - MYSQL_DATABASE=database
      - MYSQL_USER=ask
      - MYSQL_PASSWORD=ask
      - MYSQL_ROOT_PASSWORD=ask
