name: GitHub Actions Demo

on: 
  push:
    branches: [main]

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    env:
      working-directory: ./front
    steps:
      - run: npm install
      - run: eslint .
